architecture:
  attribute:
    frequency: 400
    interface: csv_cmos
    technology: 45
  module:
    pe:
      instance:
      - 32
      - 6
      query:
        class: fft_pe
      tag:
      - pe
      - array
    test:
      instance:
      - 32
      - 6
      query:
        class: test
      tag:
      - test
