architecture:
  attribute:
    frequency: 400
    interface: csv_cmos
    technology: 45
  module:
    act_mux:
      instance: &id003
      - 256
      - 256
      query:
        class: and_gate
        width: 16
      tag: &id004
      - pe
      - array
    ififo:
      instance: &id001
      - 256
      query:
        class: fifo
        depth: 64
        width: 16
      tag: &id002
      - fifo
      - array
    ofifo:
      instance: *id001
      query:
        class: fifo
        depth: 64
        width: 16
      tag: *id002
    weight_mux:
      instance: *id003
      query:
        class: and_gate
        width: 16
      tag: *id004
