architecture:
  attribute:
    frequency: 400
    interface: csv_cmos
    technology: 45
  module:
    ififo:
      instance:
      - 16
      query:
        class: fifo
        depth: 16
        width: 16
      tag:
      - fifo
      - array
    isram:
      instance:
      - 1
      query:
        bank: 4
        class: sram
        depth: 128
        interface: cacti7
        width: 128
      tag:
      - memory
    ofifo:
      instance:
      - 16
      query:
        class: fifo
        depth: 16
        width: 16
      tag:
      - fifo
      - array
    osram:
      instance:
      - 1
      query:
        bank: 4
        class: sram
        depth: 128
        interface: cacti7
        width: 128
      tag:
      - memory
    output_adder:
      instance:
      - 16
      query:
        class: adder_bfloat16
      tag:
      - output_adder
      - array
    pe:
      instance:
      - 16
      - 16
      query:
        class: systolic_pe
      tag:
      - pe
      - array
    wfifo:
      instance:
      - 16
      query:
        class: fifo
        depth: 16
        width: 16
      tag:
      - fifo
      - array
    wsram:
      instance:
      - 1
      query:
        bank: 4
        class: sram
        depth: 128
        interface: cacti7
        width: 128
      tag:
      - memory
