architecture:
  attribute:
    frequency: 400
    interface: csv_cmos
    technology: 45
  module:
    ififo:
      instance:
      - 32
      query:
        class: fifo
        depth: 32
        width: 16
      tag:
      - fifo
      - array
    isram:
      instance:
      - 1
      query:
        bank: 4
        class: sram
        depth: 256
        interface: cacti7
        width: 256
      tag:
      - memory
    ofifo:
      instance:
      - 32
      query:
        class: fifo
        depth: 32
        width: 16
      tag:
      - fifo
      - array
    osram:
      instance:
      - 1
      query:
        bank: 4
        class: sram
        depth: 256
        interface: cacti7
        width: 256
      tag:
      - memory
    output_adder:
      instance:
      - 32
      query:
        class: adder_bfloat16
      tag:
      - output_adder
      - array
    pe:
      instance:
      - 32
      - 32
      query:
        class: systolic_pe
      tag:
      - pe
      - array
    wfifo:
      instance:
      - 32
      query:
        class: fifo
        depth: 32
        width: 16
      tag:
      - fifo
      - array
    wsram:
      instance:
      - 1
      query:
        bank: 4
        class: sram
        depth: 256
        interface: cacti7
        width: 256
      tag:
      - memory
