architecture:
  attribute:
    frequency: 400
    interface: csv_cmos
    technology: 45
  module:
    acc_en_reg:
      instance:
      - 8
      - 8
      - 64
      - 64
      query:
        class: register
        width: 1
      tag:
      - pe
      - control
      - array
    accumulator:
      instance:
      - 8
      - 8
      - 64
      query:
        class: adder_bfloat16
      tag:
      - output_adder
      - array
    accumulator_reg:
      instance:
      - 8
      - 8
      - 64
      query:
        class: register
        width: 16
      tag:
      - output_register
      - array
    act_en_reg:
      instance:
      - 8
      - 8
      - 64
      - 64
      query:
        class: register
        width: 1
      tag:
      - pe
      - control
      - array
    act_mux:
      instance:
      - 8
      - 8
      - 64
      - 64
      query:
        class: and_gate
        width: 16
      tag:
      - pe
      - array
    act_reg:
      instance:
      - 8
      - 8
      - 64
      - 64
      query:
        class: register
        width: 16
      tag:
      - pe
      - data
      - array
    add_mux:
      instance:
      - 8
      - 8
      - 64
      - 64
      query:
        class: and_gate
        width: 16
      tag:
      - pe
      - array
    adder:
      instance:
      - 8
      - 8
      - 64
      - 64
      query:
        class: adder_bfloat16
      tag:
      - pe
      - mac
      - array
    ififo:
      instance:
      - 8
      - 8
      - 64
      query:
        class: fifo
        depth: 64
        width: 16
      tag:
      - fifo
      - array
    mult_en_reg:
      instance:
      - 8
      - 8
      - 64
      - 64
      query:
        class: register
        width: 1
      tag:
      - pe
      - control
      - array
    multiplier:
      instance:
      - 8
      - 8
      - 64
      - 64
      query:
        class: multiplier_bfloat16
      tag:
      - pe
      - mac
      - array
    ofifo:
      instance:
      - 8
      - 8
      - 64
      query:
        class: fifo
        depth: 64
        width: 16
      tag:
      - fifo
      - array
    sram:
      instance:
      - 29
      query:
        bank: 512
        class: sram
        depth: 8192
        interface: cacti7
        width: 16
      tag:
      - memory
    sum_en_reg:
      instance:
      - 8
      - 8
      - 64
      - 64
      query:
        class: register
        width: 1
      tag:
      - pe
      - control
      - array
    sum_mux:
      instance:
      - 8
      - 8
      - 64
      - 64
      query:
        class: and_gate
        width: 16
      tag:
      - pe
      - array
    sum_reg:
      instance:
      - 8
      - 8
      - 64
      - 64
      query:
        class: register
        width: 16
      tag:
      - pe
      - data
      - array
    vector_adder:
      instance:
      - 8
      - 8
      - 64
      query:
        class: adder_bfloat16
      tag:
      - vector
      - array
    vector_multiplier:
      instance:
      - 8
      - 8
      - 64
      query:
        class: multiplier_bfloat16
      tag:
      - vector
      - array
    vector_reg:
      instance:
      - 8
      - 8
      - 64
      query:
        class: register
        width: 16
      tag:
      - vector
      - array
    weight_en_reg:
      instance:
      - 8
      - 8
      - 64
      - 64
      query:
        class: register
        width: 1
      tag:
      - pe
      - control
      - array
    weight_mux:
      instance:
      - 8
      - 8
      - 64
      - 64
      query:
        class: and_gate
        width: 16
      tag:
      - pe
      - array
    weight_path_en_reg:
      instance:
      - 8
      - 8
      - 64
      - 64
      query:
        class: register
        width: 1
      tag:
      - pe
      - control
      - array
    weight_path_reg:
      instance:
      - 8
      - 8
      - 64
      - 64
      query:
        class: register
        width: 16
      tag:
      - pe
      - data
      - array
    weight_reg:
      instance:
      - 8
      - 8
      - 64
      - 64
      query:
        class: register
        width: 16
      tag:
      - pe
      - data
      - array
    wfifo:
      instance:
      - 8
      - 8
      - 64
      query:
        class: fifo
        depth: 64
        width: 16
      tag:
      - fifo
      - array
