workload:
  gemm_config_1:
    k: 128
    m: 128
    n: 128
  gemm_config_2:
    k: 1024
    m: 1024
    n: 1024
  gemm_config_3:
    k: 1024
    m: 1024
    n: 1024
  gemm_config_4:
    batch_size: 8
    dim:
    - 64
    - 64
    - 64
