workload:
  gemm_config_1:
    k: 64
    m: 64
    n: 64
  gemm_config_2:
    k: 512
    m: 512
    n: 512
  gemm_config_3:
    k: 1024
    m: 1024
    n: 1024
  gemm_config_4:
    batch_size: 4
    dim:
    - 64
    - 64
    - 64
