architecture:
  attribute:
    technology: 45
    frequency: 400
    interface: csv_cmos
  module:
    isram:
      instance:
      - 1
      tag:
      - memory
      query:
        width: 64
        depth: 64
    wsram:
      instance:
      - 1
      tag:
      - memory
      query:
        width: 64
        depth: 64
    osram:
      instance:
      - 1
      tag:
      - memory
      query:
        width: 64
        depth: 64
    ififo:
      tag:
      - fifo
      - array
      query:
        depth: 8
      instance:
      - 8
    wfifo:
      tag:
      - fifo
      - array
      query:
        depth: 8
      instance:
      - 8
    ofifo:
      tag:
      - fifo
      - array
      query:
        depth: 8
      instance:
      - 8
    output_adder:
      tag:
      - output_adder
      - array
      query:
        class: adder_bfloat16
      instance:
      - 8
    multiplier:
      tag:
      - pe
      - mac
      - array
      query:
        class: multiplier_bfloat16
      instance:
      - 8
      - 8
    adder:
      tag:
      - pe
      - mac
      - array
      query:
        class: adder_bfloat16
      instance:
      - 8
      - 8
    act_en_reg:
      tag:
      - pe
      - control
      - array
      query:
        width: 1
      instance:
      - 8
      - 8
    mult_en_reg:
      tag:
      - pe
      - control
      - array
      query:
        width: 1
      instance:
      - 8
      - 8
    acc_en_reg:
      tag:
      - pe
      - control
      - array
      query:
        width: 1
      instance:
      - 8
      - 8
    weight_path_en_reg:
      tag:
      - pe
      - control
      - array
      query:
        width: 1
      instance:
      - 8
      - 8
    weight_en_reg:
      tag:
      - pe
      - control
      - array
      query:
        width: 1
      instance:
      - 8
      - 8
    sum_en_reg:
      tag:
      - pe
      - control
      - array
      query:
        width: 1
      instance:
      - 8
      - 8
    act_reg:
      tag:
      - pe
      - data
      - array
      query:
        width: 16
      instance:
      - 8
      - 8
    weight_path_reg:
      tag:
      - pe
      - data
      - array
      query:
        width: 16
      instance:
      - 8
      - 8
    sum_reg:
      tag:
      - pe
      - data
      - array
      query:
        width: 16
      instance:
      - 8
      - 8
    weight_reg:
      tag:
      - pe
      - data
      - array
      query:
        width: 16
      instance:
      - 8
      - 8
    act_mux:
      tag:
      - pe
      - array
      query:
        width: 16
      instance:
      - 8
      - 8
    weight_mux:
      tag:
      - pe
      - array
      query:
        width: 16
      instance:
      - 8
      - 8
    add_mux:
      tag:
      - pe
      - array
      query:
        width: 16
      instance:
      - 8
      - 8
    sum_mux:
      tag:
      - pe
      - array
      query:
        width: 16
      instance:
      - 8
      - 8
