architecture:
  attribute:
    technology: 45
    frequency: 400
    interface: csv_cmos
  module:
    isram:
      instance:
      - 1
      tag:
      - memory
      query:
        class: sram
        interface: cacti7
        bank: 2
        width: 128
        depth: 128
    wsram:
      instance:
      - 1
      tag:
      - memory
      query:
        class: sram
        interface: cacti7
        bank: 2
        width: 128
        depth: 128
    osram:
      instance:
      - 1
      tag:
      - memory
      query:
        class: sram
        interface: cacti7
        bank: 2
        width: 128
        depth: 128
    ififo:
      tag:
      - fifo
      - array
      query:
        class: fifo
        width: 16
        depth: 16
      instance:
      - 16
    wfifo:
      tag:
      - fifo
      - array
      query:
        class: fifo
        width: 16
        depth: 16
      instance:
      - 16
    ofifo:
      tag:
      - fifo
      - array
      query:
        class: fifo
        width: 16
        depth: 16
      instance:
      - 16
    output_adder:
      tag:
      - output_adder
      - array
      query:
        class: adder_bfloat16
      instance:
      - 16
    multiplier:
      tag:
      - pe
      - mac
      - array
      query:
        class: multiplier_bfloat16
      instance:
      - 16
      - 16
    adder:
      tag:
      - pe
      - mac
      - array
      query:
        class: adder_bfloat16
      instance:
      - 16
      - 16
    act_en_reg:
      tag:
      - pe
      - control
      - array
      query:
        class: register
        width: 1
      instance:
      - 16
      - 16
    mult_en_reg:
      tag:
      - pe
      - control
      - array
      query:
        class: register
        width: 1
      instance:
      - 16
      - 16
    acc_en_reg:
      tag:
      - pe
      - control
      - array
      query:
        class: register
        width: 1
      instance:
      - 16
      - 16
    weight_path_en_reg:
      tag:
      - pe
      - control
      - array
      query:
        class: register
        width: 1
      instance:
      - 16
      - 16
    weight_en_reg:
      tag:
      - pe
      - control
      - array
      query:
        class: register
        width: 1
      instance:
      - 16
      - 16
    sum_en_reg:
      tag:
      - pe
      - control
      - array
      query:
        class: register
        width: 1
      instance:
      - 16
      - 16
    act_reg:
      tag:
      - pe
      - data
      - array
      query:
        class: register
        width: 16
      instance:
      - 16
      - 16
    weight_path_reg:
      tag:
      - pe
      - data
      - array
      query:
        class: register
        width: 16
      instance:
      - 16
      - 16
    sum_reg:
      tag:
      - pe
      - data
      - array
      query:
        class: register
        width: 16
      instance:
      - 16
      - 16
    weight_reg:
      tag:
      - pe
      - data
      - array
      query:
        class: register
        width: 16
      instance:
      - 16
      - 16
    act_mux:
      tag:
      - pe
      - array
      query:
        class: and_gate
        width: 16
      instance:
      - 16
      - 16
    weight_mux:
      tag:
      - pe
      - array
      query:
        class: and_gate
        width: 16
      instance:
      - 16
      - 16
    add_mux:
      tag:
      - pe
      - array
      query:
        class: and_gate
        width: 16
      instance:
      - 16
      - 16
    sum_mux:
      tag:
      - pe
      - array
      query:
        class: and_gate
        width: 16
      instance:
      - 16
      - 16
