architecture:
  attribute:
    technology: 45
    frequency: 400
    interface: csv_cmos
  module:
    isram:
      instance:
      - 1
      tag:
      - memory
      query:
        width: 32
        depth: 32
    wsram:
      instance:
      - 1
      tag:
      - memory
      query:
        width: 32
        depth: 32
    osram:
      instance:
      - 1
      tag:
      - memory
      query:
        width: 32
        depth: 32
    ififo:
      tag:
      - fifo
      - array
      query:
        depth: 4
      instance:
      - 4
    wfifo:
      tag:
      - fifo
      - array
      query:
        depth: 4
      instance:
      - 4
    ofifo:
      tag:
      - fifo
      - array
      query:
        depth: 4
      instance:
      - 4
    output_adder:
      tag:
      - output_adder
      - array
      query:
        class: adder_bfloat16
      instance:
      - 4
    multiplier:
      tag:
      - pe
      - mac
      - array
      query:
        class: multiplier_bfloat16
      instance:
      - 4
      - 4
    adder:
      tag:
      - pe
      - mac
      - array
      query:
        class: adder_bfloat16
      instance:
      - 4
      - 4
    act_en_reg:
      tag:
      - pe
      - control
      - array
      query:
        width: 1
      instance:
      - 4
      - 4
    mult_en_reg:
      tag:
      - pe
      - control
      - array
      query:
        width: 1
      instance:
      - 4
      - 4
    acc_en_reg:
      tag:
      - pe
      - control
      - array
      query:
        width: 1
      instance:
      - 4
      - 4
    weight_path_en_reg:
      tag:
      - pe
      - control
      - array
      query:
        width: 1
      instance:
      - 4
      - 4
    weight_en_reg:
      tag:
      - pe
      - control
      - array
      query:
        width: 1
      instance:
      - 4
      - 4
    sum_en_reg:
      tag:
      - pe
      - control
      - array
      query:
        width: 1
      instance:
      - 4
      - 4
    act_reg:
      tag:
      - pe
      - data
      - array
      query:
        width: 16
      instance:
      - 4
      - 4
    weight_path_reg:
      tag:
      - pe
      - data
      - array
      query:
        width: 16
      instance:
      - 4
      - 4
    sum_reg:
      tag:
      - pe
      - data
      - array
      query:
        width: 16
      instance:
      - 4
      - 4
    weight_reg:
      tag:
      - pe
      - data
      - array
      query:
        width: 16
      instance:
      - 4
      - 4
    act_mux:
      tag:
      - pe
      - array
      query:
        width: 16
      instance:
      - 4
      - 4
    weight_mux:
      tag:
      - pe
      - array
      query:
        width: 16
      instance:
      - 4
      - 4
    add_mux:
      tag:
      - pe
      - array
      query:
        width: 16
      instance:
      - 4
      - 4
    sum_mux:
      tag:
      - pe
      - array
      query:
        width: 16
      instance:
      - 4
      - 4
