architecture:
  module:
    act_reg:
      tag:
      - pe
      - data
      - array
      instance:
      - 32
      - 32
      query:
        width: 16
        class: register
    acc_en_reg:
      tag:
      - pe
      - control
      - array
      instance:
      - 32
      - 32
      query:
        width: 1
        class: register
    multiplier:
      tag:
      - pe
      - mac
      - array
      instance:
      - 32
      - 32
      query:
        class: multiplier_bfloat16
    weight_path_reg:
      tag:
      - pe
      - data
      - array
      instance:
      - 32
      - 32
      query:
        width: 16
        class: register
    sum_en_reg:
      tag:
      - pe
      - control
      - array
      instance:
      - 32
      - 32
      query:
        width: 1
        class: register
    osram:
      tag:
      - memory
      instance:
      - 1
      query:
        depth: 256
        bank: 2
        width: 256
        interface: cacti7
        class: sram
    add_mux:
      tag:
      - pe
      - array
      instance:
      - 32
      - 32
      query:
        width: 16
        class: and_gate
    act_en_reg:
      tag:
      - pe
      - control
      - array
      instance:
      - 32
      - 32
      query:
        width: 1
        class: register
    mult_en_reg:
      tag:
      - pe
      - control
      - array
      instance:
      - 32
      - 32
      query:
        width: 1
        class: register
    adder:
      tag:
      - pe
      - mac
      - array
      instance:
      - 32
      - 32
      query:
        class: adder_bfloat16
    weight_path_en_reg:
      tag:
      - pe
      - control
      - array
      instance:
      - 32
      - 32
      query:
        width: 1
        class: register
    wfifo:
      tag:
      - fifo
      - array
      instance:
      - 32
      query:
        width: 16
        depth: 32
        class: fifo
    sum_reg:
      tag:
      - pe
      - data
      - array
      instance:
      - 32
      - 32
      query:
        width: 16
        class: register
    wsram:
      tag:
      - memory
      instance:
      - 1
      query:
        depth: 256
        bank: 2
        width: 256
        interface: cacti7
        class: sram
    isram:
      tag:
      - memory
      instance:
      - 1
      query:
        depth: 256
        bank: 2
        width: 256
        interface: cacti7
        class: sram
    weight_reg:
      tag:
      - pe
      - data
      - array
      instance:
      - 32
      - 32
      query:
        width: 16
        class: register
    ofifo:
      tag:
      - fifo
      - array
      instance:
      - 32
      query:
        width: 16
        depth: 32
        class: fifo
    act_mux:
      tag:
      - pe
      - array
      instance:
      - 32
      - 32
      query:
        width: 16
        class: and_gate
    ififo:
      tag:
      - fifo
      - array
      instance:
      - 32
      query:
        width: 16
        depth: 32
        class: fifo
    weight_mux:
      tag:
      - pe
      - array
      instance:
      - 32
      - 32
      query:
        width: 16
        class: and_gate
    output_adder:
      tag:
      - output_adder
      - array
      instance:
      - 32
      query:
        class: adder_bfloat16
    sum_mux:
      tag:
      - pe
      - array
      instance:
      - 32
      - 32
      query:
        width: 16
        class: and_gate
    weight_en_reg:
      tag:
      - pe
      - control
      - array
      instance:
      - 32
      - 32
      query:
        width: 1
        class: register
  attribute:
    interface: csv_cmos
    technology: 45
    frequency: 400
