architecture:
  attribute:
    frequency: 100
    interface: csv_cmos
    technology: 7
  module:
    WTA:
      instance:
      - 1
      query:
        class: wta
      tag:
      - column
      - wta
    edge2pulse:
      instance:
      - 1
      query:
        class: edge2pulse
      tag:
      - column
    fsm_simple:
      instance:
      - 2
      query:
        class: fsm_simple
      tag:
      - column
    fsm_synapse:
      instance:
      - 343
      - 2
      query:
        class: fsm_synapse
      tag:
      - column
    neuron:
      instance:
      - 2
      query:
        class: pac
        width: 343
      tag:
      - column
    pulse2edge:
      instance:
      - 1
      query:
        class: pulse2edge_96
        width: 345
      tag:
      - column
    stdp:
      instance:
      - 343
      - 2
      query:
        class: stdp
      tag:
      - column
    top_reg:
      instance:
      - 1
      query:
        class: tnn_reg_3
        width: 1
      tag:
      - column
