workload:
  vgg16:
    configuration:
      bitwidth: 4
      conv3-128:
      - 3
      - 3
      - 128
      conv3-128_of:
      - - 112
        - 112
        - 128
      - - 112
        - 112
        - 128
      conv3-256:
      - 3
      - 3
      - 256
      conv3-256_of:
      - - 56
        - 56
        - 256
      - - 56
        - 56
        - 256
      - - 56
        - 56
        - 256
      conv3-512:
      - 3
      - 3
      - 512
      conv3-512_of:
      - - 28
        - 28
        - 512
      - - 28
        - 28
        - 512
      - - 28
        - 28
        - 512
      - - 14
        - 14
        - 512
      - - 14
        - 14
        - 512
      - - 14
        - 14
        - 512
      conv3-64:
      - 3
      - 3
      - 64
      conv3-64_of:
      - - 224
        - 224
        - 64
      - - 224
        - 224
        - 64
