architecture:
  attribute:
    frequency: 400
    interface: csv_cmos
    technology: 45
  module:
    adderA:
      instance:
      - 8
      - 4
      query:
        class: adder_8
        width: 64
      tag:
      - adder
      - array
    adderB:
      instance:
      - 8
      - 4
      query:
        class: adder_8
        width: 64
      tag:
      - adder
      - array
    multiplier:
      instance:
      - 8
      - 4
      query:
        class: mult_4
        width: 32
      tag:
      - multiplier
      - array
    not_gate:
      instance:
      - 8
      - 4
      query:
        class: not_gate
      tag:
      - not_gate
      - array
    regA:
      instance:
      - 8
      - 4
      query:
        class: register
        width: 32
      tag:
      - register
      - array
    regB:
      instance:
      - 8
      - 4
      query:
        class: register
        width: 32
      tag:
      - register
      - array
